registration-service:
  environment: 'prod'
  replicas: 3
  verification:
    enabled: 'true'
    excluded-email-domains: 'redhat.com'
  auth-client:
    library-url: 'http://129.40.58.177:8082/auth/js/keycloak.js'
    config-raw: '{
                  "realm": "redhat-external",
                  "auth-server-url": "http://129.40.58.177:8082/auth",
                  "ssl-required": "none",
                  "resource": "gatekeeper",
                  "clientId": "gatekeeper",
                  "public-client": true
                }'
    public-keys-url: 'http://129.40.58.177:8082/auth/realms/local/protocol/openid-connect/certs'
host-operator:
  secret:
    name: host-operator-secret
  config-map:
    name: host-operator-config
